### ISSUE TITLE
Empty repository

### ISSUE THREAD

**Issue by martinRenou** [conda-forge/ipycanvas-feedstock#1]
@conda-forge/core there seems to have been an issue while creating this repository... It is empty. Could someone fix it? Thanks a lot!!

**Comment by scopatz** [comment]
Yeah, It is being worked on

**Comment by martinRenou** [comment]
Thanks a lot!

**Comment by martinRenou** [comment]
Thanks again 😊

**Comment by scopatz** [comment]
np!
